
# 系统安全日志文件
secure_log: /var/log/secure
# 打印日志
log_file: ./dynamic_log.txt

# ip白名单 强烈建议配置，因为如果不配置，若别人和你在同一公网ip下，他多次尝试登陆并失败，会使得ip被封，使得你自己也无法访问
allow_ip:
  - 127.0.0.1
  - 202.197.74.82
  - 119.28.22.215 # 腾讯云ssh
  - 39.144.0.0/16



# 规则访问 该程序，处理通过22端口尝试登陆访问的ip
rules:
  # 地区以 http://ip-api.com/json/?lang=zh-CN 查询的结果为准
  # 中国ip 120秒超过5次 加入防火墙 port可填只封锁22端口，填-1则为封锁此ip访问所有端口
  -
    port: -1
    country: 中国
    regionName:
    city:
    time: 120
    count: 5

  # 其它地区ip 直接加入防火墙
  -
    port: -1
    country:
    regionName:
    city:
    time: 1
    count: 0

